OBJ=AppError.o Bargain.o Hand.o IOMgmt.o Move.o SimMgmt.o SoLongSuckerApp.o Stack.o

all : SoLongSuckerApp

SoLongSuckerApp : $(OBJ)
	$(CXX) $(OBJ) -o SoLongSuckerApp $(CXXFLAGS)

clean :
	rm -f *.o SoLongSuckerApp

