OBJ=AppError.o Bargain.o BargainMsg.o Board.o ChipMsg.o CustomPlayer.o Hand.o IOMgmt.o JacobJerk.o MoveProposal.o NancyNice.o Pile.o Player.o PlayersMsg.cpp RandyRandom.o SimMgmt.o SoLongSucker.o SoLongSuckerApp.o 

all : SoLongSuckerApp

SoLongSuckerApp : $(OBJ)
	$(CXX) $(OBJ) -o SoLongSuckerApp $(CXXFLAGS)

clean :
	rm -f *.o SoLongSuckerApp

